// src/config/moduleConfig.js
import React from 'react';

// Importar todos los componentes
import { Dashboard } from '../pages/Dashboard';
import { Analytics } from '../pages/Analytics';
import { Users } from '../pages/Users';
import { UserRoles } from '../pages/UserRoles';
import { UserPermissions } from '../pages/UserPermissions';
import { Customers } from '../pages/Customers';
import { Statistics } from '../pages/Statistics';
import { DataPage } from '../pages/DataPage';
import { ChartPage } from '../pages/ChartPage';
import { Chat } from '../pages/Chat';
import { Kanban } from '../pages/Kanban';
import { Mail } from '../pages/Mail';
import { Calendar } from '../pages/Calendar';
import { Modules } from '../pages/Modules';
import { Settings } from '../pages/Settings';

// Importar iconos de Material-UI
import {
  Dashboard as DashboardIcon,
  BarChart as BarChartIcon,
  TrendingUp as TrendingUpIcon,
  Storage as StorageIcon,
  PieChart as PieChartIcon,
  People as PeopleIcon,
  Security as SecurityIcon,
  VpnKey as VpnKeyIcon,
  Group as GroupIcon,
  Person as PersonIcon,
  Chat as ChatIcon,
  ViewKanban as ViewKanbanIcon,
  Mail as MailIcon,
  CalendarToday as CalendarTodayIcon,
  Article as ArticleIcon,
  Settings as SettingsIcon,
  Apps as AppsIcon,
  Widgets as WidgetsIcon,
  Category as CategoryIcon,
  List as ListIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Assessment as AssessmentIcon,
  Business as BusinessIcon,
  ShoppingCart as ShoppingCartIcon,
  Inventory as InventoryIcon,
  Receipt as ReceiptIcon,
  AccountBox as AccountBoxIcon,
  SupervisorAccount as SupervisorAccountIcon,
  AdminPanelSettings as AdminPanelSettingsIcon,
  ManageAccounts as ManageAccountsIcon,
  Folder as FolderIcon,
  Description as DescriptionIcon,
  Home as HomeIcon,
  Info as InfoIcon,
  Help as HelpIcon,
  ContactSupport as ContactSupportIcon,
  Notifications as NotificationsIcon,
  Language as LanguageIcon,
  Public as PublicIcon,
  Work as WorkIcon,
  School as SchoolIcon,
  LocalHospital as LocalHospitalIcon,
  Restaurant as RestaurantIcon,
  Hotel as HotelIcon,
  DirectionsCar as DirectionsCarIcon,
  Flight as FlightIcon,
  Train as TrainIcon,
  LocalShipping as LocalShippingIcon,
  Store as StoreIcon,
  Storefront as StorefrontIcon,
  ShoppingBag as ShoppingBagIcon,
  Payment as PaymentIcon,
  AccountBalance as AccountBalanceIcon,
  CreditCard as CreditCardIcon,
  MonetizationOn as MonetizationOnIcon,
  TrendingDown as TrendingDownIcon,
  ShowChart as ShowChartIcon,
  Timeline as TimelineIcon,
  DonutLarge as DonutLargeIcon,
  BubbleChart as BubbleChartIcon,
  MultilineChart as MultilineChartIcon,
  StackedLineChart as StackedLineChartIcon,
  WaterfallChart as WaterfallChartIcon,
  ScatterPlot as ScatterPlotIcon,
  DataUsage as DataUsageIcon,
  Analytics as AnalyticsIcon,
  Speed as SpeedIcon,
  Memory as MemoryIcon,
  Computer as ComputerIcon,
  PhoneAndroid as PhoneAndroidIcon,
  Tablet as TabletIcon,
  Watch as WatchIcon,
  Tv as TvIcon,
  Speaker as SpeakerIcon,
  Headphones as HeadphonesIcon,
  Camera as CameraIcon,
  Videocam as VideocamIcon,
  MusicNote as MusicNoteIcon,
  Movie as MovieIcon,
  Image as ImageIcon,
  PhotoLibrary as PhotoLibraryIcon,
  Collections as CollectionsIcon,
  Palette as PaletteIcon,
  Brush as BrushIcon,
  FormatPaint as FormatPaintIcon,
  ColorLens as ColorLensIcon,
  Gradient as GradientIcon,
  AutoAwesome as AutoAwesomeIcon,
  Star as StarIcon,
  Favorite as FavoriteIcon,
  ThumbUp as ThumbUpIcon,
  Share as ShareIcon,
  BookmarkBorder as BookmarkBorderIcon,
  Flag as FlagIcon,
  Label as LabelIcon,
  LocalOffer as LocalOfferIcon,
  Loyalty as LoyaltyIcon,
  CardGiftcard as CardGiftcardIcon,
  Redeem as RedeemIcon,
  ConfirmationNumber as ConfirmationNumberIcon,
  Event as EventIcon,
  Today as TodayIcon,
  DateRange as DateRangeIcon,
  Schedule as ScheduleIcon,
  AccessTime as AccessTimeIcon,
  Timer as TimerIcon,
  Alarm as AlarmIcon,
  AlarmOn as AlarmOnIcon,
  Snooze as SnoozeIcon,
  TimeToLeave as TimeToLeaveIcon,
  Update as UpdateIcon,
  History as HistoryIcon,
  Restore as RestoreIcon,
  Backup as BackupIcon,
  CloudUpload as CloudUploadIcon,
  CloudDownload as CloudDownloadIcon,
  CloudSync as CloudSyncIcon,
  CloudQueue as CloudQueueIcon,
  CloudOff as CloudOffIcon,
  WifiOff as WifiOffIcon,
  SignalWifiOff as SignalWifiOffIcon,
  NetworkCheck as NetworkCheckIcon,
  Router as RouterIcon,
  DeviceHub as DeviceHubIcon,
  Dns as DnsIcon,
  VpnLock as VpnLockIcon,
  Https as HttpsIcon,
  Lock as LockIcon,
  LockOpen as LockOpenIcon,
  Key as KeyIcon,
  Password as PasswordIcon,
  Fingerprint as FingerprintIcon,
  Face as FaceIcon,
  VisibilityOff as VisibilityOffIcon,
  Visibility as VisibilityIcon,
  RemoveRedEye as RemoveRedEyeIcon,
  Preview as PreviewIcon,
  Search as SearchIcon,
  FindInPage as FindInPageIcon,
  FindReplace as FindReplaceIcon,
  Zoom as ZoomIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Fullscreen as FullscreenIcon,
  FullscreenExit as FullscreenExitIcon,
  AspectRatio as AspectRatioIcon,
  CropFree as CropFreeIcon,
  Crop as CropIcon,
  Transform as TransformIcon,
  Tune as TuneIcon,
  FilterList as FilterListIcon,
  Sort as SortIcon,
  ImportExport as ImportExportIcon,
  SwapVert as SwapVertIcon,
  SwapHoriz as SwapHorizIcon,
  CompareArrows as CompareArrowsIcon,
  Code as CodeIcon,
  Terminal as TerminalIcon,
  DeveloperMode as DeveloperModeIcon,
  BugReport as BugReportIcon,
  Build as BuildIcon,
  Construction as ConstructionIcon,
  Engineering as EngineeringIcon,
  Handyman as HandymanIcon,
  Extension as ExtensionIcon,
  Plugin as PluginIcon,
  Api as ApiIcon,
  Integration as IntegrationIcon,
  Hub as HubIcon,
  AccountTree as AccountTreeIcon,
  Schema as SchemaIcon,
  DataObject as DataObjectIcon,
  Functions as FunctionsIcon,
  Memory as MemoryIcon2,
  Storage as StorageIcon2,
  Database as DatabaseIcon,
  TableChart as TableChartIcon,
  ViewList as ViewListIcon,
  ViewModule as ViewModuleIcon,
  ViewQuilt as ViewQuiltIcon,
  ViewStream as ViewStreamIcon,
  ViewArray as ViewArrayIcon,
  ViewColumn as ViewColumnIcon,
  ViewCarousel as ViewCarouselIcon,
  ViewComfy as ViewComfyIcon,
  ViewCompact as ViewCompactIcon,
  ViewAgenda as ViewAgendaIcon,
  ViewDay as ViewDayIcon,
  ViewWeek as ViewWeekIcon,
  CalendarViewDay as CalendarViewDayIcon,
  CalendarViewWeek as CalendarViewWeekIcon,
  CalendarViewMonth as CalendarViewMonthIcon,
  EventNote as EventNoteIcon,
  EventAvailable as EventAvailableIcon,
  EventBusy as EventBusyIcon,
  EventSeat as EventSeatIcon,
  MeetingRoom as MeetingRoomIcon,
  Room as RoomIcon,
  RoomService as RoomServiceIcon,
  Bed as BedIcon,
  Bathtub as BathtubIcon,
  Shower as ShowerIcon,
  Kitchen as KitchenIcon,
  Dining as DiningIcon,
  LivingIcon,
  Weekend as WeekendIcon,
  Chair as ChairIcon,
  Desk as DeskIcon,
  Table as TableIcon,
  Couch as CouchIcon,
  Bed as BedIcon2,
  SingleBed as SingleBedIcon,
  KingBed as KingBedIcon,
  Crib as CribIcon,
  Baby as BabyIcon,
  ChildCare as ChildCareIcon,
  School as SchoolIcon2,
  MenuBook as MenuBookIcon,
  Book as BookIcon,
  LibraryBooks as LibraryBooksIcon,
  AutoStories as AutoStoriesIcon,
  ImportContacts as ImportContactsIcon,
  ChromeReaderMode as ChromeReaderModeIcon,
  Article as ArticleIcon2,
  Description as DescriptionIcon2,
  Note as NoteIcon,
  NoteAdd as NoteAddIcon,
  Edit as EditIcon2,
  EditNote as EditNoteIcon,
  Create as CreateIcon,
  Draw as DrawIcon,
  Gesture as GestureIcon,
  TouchApp as TouchAppIcon,
  PanTool as PanToolIcon,
  Back as BackIcon,
  Undo as UndoIcon,
  Redo as RedoIcon,
  Refresh as RefreshIcon,
  Sync as SyncIcon,
  Loop as LoopIcon,
  Repeat as RepeatIcon,
  RepeatOne as RepeatOneIcon,
  Shuffle as ShuffleIcon,
  SkipPrevious as SkipPreviousIcon,
  SkipNext as SkipNextIcon,
  FastRewind as FastRewindIcon,
  FastForward as FastForwardIcon,
  PlayArrow as PlayArrowIcon,
  Pause as PauseIcon,
  Stop as StopIcon,
  Replay as ReplayIcon,
  Forward10 as Forward10Icon,
  Replay10 as Replay10Icon,
  Forward30 as Forward30Icon,
  Replay30 as Replay30Icon,
  Speed as SpeedIcon2,
  SlowMotionVideo as SlowMotionVideoIcon,
  HighQuality as HighQualityIcon,
  Hd as HdIcon,
  FourK as FourKIcon,
  EightK as EightKIcon,
  VideoSettings as VideoSettingsIcon,
  Subtitles as SubtitlesIcon,
  ClosedCaption as ClosedCaptionIcon,
  VolumeUp as VolumeUpIcon,
  VolumeDown as VolumeDownIcon,
  VolumeMute as VolumeMuteIcon,
  VolumeOff as VolumeOffIcon,
  Mic as MicIcon,
  MicOff as MicOffIcon,
  MicNone as MicNoneIcon,
  MicExternalOn as MicExternalOnIcon,
  MicExternalOff as MicExternalOffIcon,
  RecordVoiceOver as RecordVoiceOverIcon,
  VoiceChat as VoiceChatIcon,
  VoiceOverOff as VoiceOverOffIcon,
  Hearing as HearingIcon,
  HearingDisabled as HearingDisabledIcon,
  AssistiveMotionTechnology as AssistiveMotionTechnologyIcon,
  Accessible as AccessibleIcon,
  AccessibleForward as AccessibleForwardIcon,
  Wheelchair as WheelchairIcon,
  ElderlyCare as ElderlyCareIcon,
  HealthAndSafety as HealthAndSafetyIcon,
  MedicalServices as MedicalServicesIcon,
  LocalPharmacy as LocalPharmacyIcon,
  Vaccines as VaccinesIcon,
  Coronavirus as CoronavirusIcon,
  Masks as MasksIcon,
  CleanHands as CleanHandsIcon,
  Sanitizer as SanitizerIcon,
  WashIcon,
  Soap as SoapIcon,
  Bathtub as BathtubIcon2,
  Shower as ShowerIcon2,
  HotTub as HotTubIcon,
  Pool as PoolIcon,
  Beach as BeachIcon,
  Waves as WavesIcon,
  Water as WaterIcon,
  WaterDrop as WaterDropIcon,
  Opacity as OpacityIcon,
  InvertColors as InvertColorsIcon,
  FormatColorFill as FormatColorFillIcon,
  FormatColorReset as FormatColorResetIcon,
  FormatColorText as FormatColorTextIcon,
  TextFields as TextFieldsIcon,
  Title as TitleIcon,
  FormatSize as FormatSizeIcon,
  FormatBold as FormatBoldIcon,
  FormatItalic as FormatItalicIcon,
  FormatUnderlined as FormatUnderlinedIcon,
  FormatStrikethrough as FormatStrikethroughIcon,
  FormatClear as FormatClearIcon,
  FormatAlignLeft as FormatAlignLeftIcon,
  FormatAlignCenter as FormatAlignCenterIcon,
  FormatAlignRight as FormatAlignRightIcon,
  FormatAlignJustify as FormatAlignJustifyIcon,
  FormatIndentIncrease as FormatIndentIncreaseIcon,
  FormatIndentDecrease as FormatIndentDecreaseIcon,
  FormatListBulleted as FormatListBulletedIcon,
  FormatListNumbered as FormatListNumberedIcon,
  FormatQuote as FormatQuoteIcon,
  Link as LinkIcon,
  LinkOff as LinkOffIcon,
  InsertLink as InsertLinkIcon,
  AttachFile as AttachFileIcon,
  Attachment as AttachmentIcon,
  InsertDriveFile as InsertDriveFileIcon,
  FileCopy as FileCopyIcon,
  FileDownload as FileDownloadIcon,
  FileUpload as FileUploadIcon,
  Folder as FolderIcon2,
  FolderOpen as FolderOpenIcon,
  FolderShared as FolderSharedIcon,
  FolderSpecial as FolderSpecialIcon,
  CreateNewFolder as CreateNewFolderIcon,
  DriveFileMove as DriveFileMoveIcon,
  DriveFileRenameOutline as DriveFileRenameOutlineIcon,
  DeleteForever as DeleteForeverIcon,
  Delete as DeleteIcon,
  DeleteOutline as DeleteOutlineIcon,
  DeleteSweep as DeleteSweepIcon,
  RestoreFromTrash as RestoreFromTrashIcon,
  Archive as ArchiveIcon,
  Unarchive as UnarchiveIcon,
  Inbox as InboxIcon,
  Outbox as OutboxIcon,
  Send as SendIcon,
  Reply as ReplyIcon,
  ReplyAll as ReplyAllIcon,
  Forward as ForwardIcon,
  MarkEmailRead as MarkEmailReadIcon,
  MarkEmailUnread as MarkEmailUnreadIcon,
  Drafts as DraftsIcon,
  MoveToInbox as MoveToInboxIcon,
  Label as LabelIcon2,
  LabelImportant as LabelImportantIcon,
  LabelOff as LabelOffIcon,
  NewLabel as NewLabelIcon,
  LocalOffer as LocalOfferIcon2,
  Sell as SellIcon,
  ShoppingCart as ShoppingCartIcon2,
  ShoppingBag as ShoppingBagIcon2,
  ShoppingBasket as ShoppingBasketIcon,
  AddShoppingCart as AddShoppingCartIcon,
  RemoveShoppingCart as RemoveShoppingCartIcon,
  ProductionQuantityLimits as ProductionQuantityLimitsIcon,
  Inventory2 as Inventory2Icon,
  Category as CategoryIcon2,
  Widgets as WidgetsIcon2,
  Extension as ExtensionIcon2,
  Apps as AppsIcon2,
  GridView as GridViewIcon,
  ViewModule as ViewModuleIcon2,
  Dashboard as DashboardIcon2,
  SpaceDashboard as SpaceDashboardIcon,
  DashboardCustomize as DashboardCustomizeIcon,
  AutoGraph as AutoGraphIcon,
  Insights as InsightsIcon,
  TrendingUp as TrendingUpIcon2,
  TrendingDown as TrendingDownIcon2,
  TrendingFlat as TrendingFlatIcon,
  ShowChart as ShowChartIcon2,
  Timeline as TimelineIcon2,
  MultilineChart as MultilineChartIcon2,
  StackedLineChart as StackedLineChartIcon2,
  AreaChart as AreaChartIcon,
  BarChart as BarChartIcon2,
  PieChart as PieChartIcon2,
  DonutLarge as DonutLargeIcon2,
  DonutSmall as DonutSmallIcon,
  BubbleChart as BubbleChartIcon2,
  ScatterPlot as ScatterPlotIcon2,
  WaterfallChart as WaterfallChartIcon2,
  Equalizer as EqualizerIcon,
  GraphicEq as GraphicEqIcon,
  BarChart3 as BarChart3Icon,
  BarChart4 as BarChart4Icon,
  Analytics as AnalyticsIcon2,
  Assessment as AssessmentIcon2,
  Poll as PollIcon,
  QueryStats as QueryStatsIcon,
  Leaderboard as LeaderboardIcon,
  TableChart as TableChartIcon2,
  DataUsage as DataUsageIcon2,
  Storage as StorageIcon3,
  Database as DatabaseIcon2,
  CloudQueue as CloudQueueIcon2,
  Cloud as CloudIcon,
  CloudDone as CloudDoneIcon,
  CloudUpload as CloudUploadIcon2,
  CloudDownload as CloudDownloadIcon2,
  CloudSync as CloudSyncIcon2,
  CloudOff as CloudOffIcon2,
  Backup as BackupIcon2,
  Restore as RestoreIcon2,
  Update as UpdateIcon2,
  SystemUpdate as SystemUpdateIcon,
  SystemUpdateAlt as SystemUpdateAltIcon,
  GetApp as GetAppIcon,
  Publish as PublishIcon,
  FileDownload as FileDownloadIcon2,
  FileUpload as FileUploadIcon2,
  Download as DownloadIcon,
  Upload as UploadIcon,
  CloudCircle as CloudCircleIcon,
  Sync as SyncIcon2,
  SyncAlt as SyncAltIcon,
  SyncDisabled as SyncDisabledIcon,
  SyncLock as SyncLockIcon,
  SyncProblem as SyncProblemIcon,
  Loop as LoopIcon2,
  Repeat as RepeatIcon2,
  RepeatOn as RepeatOnIcon,
  RepeatOneOn as RepeatOneOnIcon,
  Shuffle as ShuffleIcon2,
  ShuffleOn as ShuffleOnIcon,
  Autorenew as AutorenewIcon,
  Cached as CachedIcon,
  Refresh as RefreshIcon2,
  RotateLeft as RotateLeftIcon,
  RotateRight as RotateRightIcon,
  Rotate90DegreesCcw as Rotate90DegreesCcwIcon,
  Rotate90DegreesCw as Rotate90DegreesCwIcon,
  FlipCameraAndroid as FlipCameraAndroidIcon,
  FlipCameraIos as FlipCameraIosIcon,
  Flip as FlipIcon,
  FlipToBack as FlipToBackIcon,
  FlipToFront as FlipToFrontIcon,
  Transform as TransformIcon2,
  ThreeDRotation as ThreeDRotationIcon,
  ThreeSixty as ThreeSixtyIcon,
  ViewIn3d as ViewIn3dIcon,
  ThreeP as ThreePIcon,
  FourMp as FourMpIcon,
  FiveMp as FiveMpIcon,
  SixMp as SixMpIcon,
  SevenMp as SevenMpIcon,
  EightMp as EightMpIcon,
  NineMp as NineMpIcon,
  TenMp as TenMpIcon,
  ElevenMp as ElevenMpIcon,
  TwelveMp as TwelveMpIcon,
  ThirteenMp as ThirteenMpIcon,
  FourteenMp as FourteenMpIcon,
  FifteenMp as FifteenMpIcon,
  SixteenMp as SixteenMpIcon,
  SeventeenMp as SeventeenMpIcon,
  EighteenMp as EighteenMpIcon,
  NineteenMp as NineteenMpIcon,
  TwentyMp as TwentyMpIcon,
  TwentyOneMp as TwentyOneMpIcon,
  TwentyTwoMp as TwentyTwoMpIcon,
  TwentyThreeMp as TwentyThreeMpIcon,
  TwentyFourMp as TwentyFourMpIcon,
} from '@mui/icons-material';

// Mapeo de componentes - AQUÍ AGREGAS NUEVOS COMPONENTES
export const componentMap = {
  // Componentes existentes
  Dashboard,
  Analytics,
  Users,
  UserRoles,
  UserPermissions,
  Customers,
  Statistics,
  DataPage,
  ChartPage,
  Chat,
  Kanban,
  Mail,
  Calendar,
  Modules,
  Settings,
  
  // Agregar nuevos componentes aquí cuando los crees
  // Ejemplo:
  // ProductList,
  // ProductCreate,
  // ProductEdit,
  // InventoryDashboard,
  // CategoryList,
  // SupplierList,
  // OrderList,
  // InvoiceList,
  // ReportSales,
  // ReportInventory,
  // UserProfile,
  // CompanySettings,
  // SystemLogs,
  // BackupRestore,
  // etc...
};

// Mapeo de iconos - AQUÍ TIENES TODOS LOS ICONOS DISPONIBLES
export const iconMap = {
  // Iconos básicos del sistema
  DashboardIcon: <DashboardIcon />,
  BarChartIcon: <BarChartIcon />,
  TrendingUpIcon: <TrendingUpIcon />,
  StorageIcon: <StorageIcon />,
  PieChartIcon: <PieChartIcon />,
  PeopleIcon: <PeopleIcon />,
  SecurityIcon: <SecurityIcon />,
  VpnKeyIcon: <VpnKeyIcon />,
  GroupIcon: <GroupIcon />,
  PersonIcon: <PersonIcon />,
  ChatIcon: <ChatIcon />,
  ViewKanbanIcon: <ViewKanbanIcon />,
  MailIcon: <MailIcon />,
  CalendarTodayIcon: <CalendarTodayIcon />,
  ArticleIcon: <ArticleIcon />,
  SettingsIcon: <SettingsIcon />,
  AppsIcon: <AppsIcon />,
  WidgetsIcon: <WidgetsIcon />,
  
  // Iconos adicionales para nuevos módulos
  CategoryIcon: <CategoryIcon />,
  ListIcon: <ListIcon />,
  AddIcon: <AddIcon />,
  EditIcon: <EditIcon />,
  AssessmentIcon: <AssessmentIcon />,
  BusinessIcon: <BusinessIcon />,
  ShoppingCartIcon: <ShoppingCartIcon />,
  InventoryIcon: <InventoryIcon />,
  ReceiptIcon: <ReceiptIcon />,
  AccountBoxIcon: <AccountBoxIcon />,
  SupervisorAccountIcon: <SupervisorAccountIcon />,
  AdminPanelSettingsIcon: <AdminPanelSettingsIcon />,
  ManageAccountsIcon: <ManageAccountsIcon />,
  FolderIcon: <FolderIcon />,
  DescriptionIcon: <DescriptionIcon />,
  HomeIcon: <HomeIcon />,
  InfoIcon: <InfoIcon />,
  HelpIcon: <HelpIcon />,
  ContactSupportIcon: <ContactSupportIcon />,
  NotificationsIcon: <NotificationsIcon />,
  LanguageIcon: <LanguageIcon />,
  PublicIcon: <PublicIcon />,
  WorkIcon: <WorkIcon />,
  SchoolIcon: <SchoolIcon />,
  LocalHospitalIcon: <LocalHospitalIcon />,
  RestaurantIcon: <RestaurantIcon />,
  HotelIcon: <HotelIcon />,
  DirectionsCarIcon: <DirectionsCarIcon />,
  FlightIcon: <FlightIcon />,
  TrainIcon: <TrainIcon />,
  LocalShippingIcon: <LocalShippingIcon />,
  StoreIcon: <StoreIcon />,
  StorefrontIcon: <StorefrontIcon />,
  ShoppingBagIcon: <ShoppingBagIcon />,
  PaymentIcon: <PaymentIcon />,
  AccountBalanceIcon: <AccountBalanceIcon />,
  CreditCardIcon: <CreditCardIcon />,
  MonetizationOnIcon: <MonetizationOnIcon />,
  TrendingDownIcon: <TrendingDownIcon />,
  ShowChartIcon: <ShowChartIcon />,
  TimelineIcon: <TimelineIcon />,
  DonutLargeIcon: <DonutLargeIcon />,
  BubbleChartIcon: <BubbleChartIcon />,
  MultilineChartIcon: <MultilineChartIcon />,
  StackedLineChartIcon: <StackedLineChartIcon />,
  WaterfallChartIcon: <WaterfallChartIcon />,
  ScatterPlotIcon: <ScatterPlotIcon />,
  DataUsageIcon: <DataUsageIcon />,
  AnalyticsIcon: <AnalyticsIcon />,
  SpeedIcon: <SpeedIcon />,
  MemoryIcon: <MemoryIcon />,
  ComputerIcon: <ComputerIcon />,
  PhoneAndroidIcon: <PhoneAndroidIcon />,
  TabletIcon: <TabletIcon />,
  WatchIcon: <WatchIcon />,
  TvIcon: <TvIcon />,
  SpeakerIcon: <SpeakerIcon />,
  HeadphonesIcon: <HeadphonesIcon />,
  CameraIcon: <CameraIcon />,
  VideocamIcon: <VideocamIcon />,
  MusicNoteIcon: <MusicNoteIcon />,
  MovieIcon: <MovieIcon />,
  ImageIcon: <ImageIcon />,
  PhotoLibraryIcon: <PhotoLibraryIcon />,
  CollectionsIcon: <CollectionsIcon />,
  PaletteIcon: <PaletteIcon />,
  BrushIcon: <BrushIcon />,
  FormatPaintIcon: <FormatPaintIcon />,
  ColorLensIcon: <ColorLensIcon />,
  GradientIcon: <GradientIcon />,
  AutoAwesomeIcon: <AutoAwesomeIcon />,
  StarIcon: <StarIcon />,
  FavoriteIcon: <FavoriteIcon />,
  ThumbUpIcon: <ThumbUpIcon />,
  ShareIcon: <ShareIcon />,
  BookmarkBorderIcon: <BookmarkBorderIcon />,
  FlagIcon: <FlagIcon />,
  LabelIcon: <LabelIcon />,
  LocalOfferIcon: <LocalOfferIcon />,
  LoyaltyIcon: <LoyaltyIcon />,
  CardGiftcardIcon: <CardGiftcardIcon />,
  RedeemIcon: <RedeemIcon />,
  ConfirmationNumberIcon: <ConfirmationNumberIcon />,
  EventIcon: <EventIcon />,
  TodayIcon: <TodayIcon />,
  DateRangeIcon: <DateRangeIcon />,
  ScheduleIcon: <ScheduleIcon />,
  AccessTimeIcon: <AccessTimeIcon />,
  TimerIcon: <TimerIcon />,
  AlarmIcon: <AlarmIcon />,
  AlarmOnIcon: <AlarmOnIcon />,
  SnoozeIcon: <SnoozeIcon />,
  TimeToLeaveIcon: <TimeToLeaveIcon />,
  UpdateIcon: <UpdateIcon />,
  HistoryIcon: <HistoryIcon />,
  RestoreIcon: <RestoreIcon />,
  BackupIcon: <BackupIcon />,
  CloudUploadIcon: <CloudUploadIcon />,
  CloudDownloadIcon: <CloudDownloadIcon />,
  CloudSyncIcon: <CloudSyncIcon />,
  CloudQueueIcon: <CloudQueueIcon />,
  CloudOffIcon: <CloudOffIcon />,
  WifiOffIcon: <WifiOffIcon />,
  SignalWifiOffIcon: <SignalWifiOffIcon />,
  NetworkCheckIcon: <NetworkCheckIcon />,
  RouterIcon: <RouterIcon />,
  DeviceHubIcon: <DeviceHubIcon />,
  DnsIcon: <DnsIcon />,
  VpnLockIcon: <VpnLockIcon />,
  HttpsIcon: <HttpsIcon />,
  LockIcon: <LockIcon />,
  LockOpenIcon: <LockOpenIcon />,
  KeyIcon: <KeyIcon />,
  PasswordIcon: <PasswordIcon />,
  FingerprintIcon: <FingerprintIcon />,
  FaceIcon: <FaceIcon />,
  VisibilityOffIcon: <VisibilityOffIcon />,
  VisibilityIcon: <VisibilityIcon />,
  RemoveRedEyeIcon: <RemoveRedEyeIcon />,
  PreviewIcon: <PreviewIcon />,
  SearchIcon: <SearchIcon />,
  FindInPageIcon: <FindInPageIcon />,
  FindReplaceIcon: <FindReplaceIcon />,
  ZoomIcon: <ZoomIcon />,
  ZoomInIcon: <ZoomInIcon />,
  ZoomOutIcon: <ZoomOutIcon />,
  FullscreenIcon: <FullscreenIcon />,
  FullscreenExitIcon: <FullscreenExitIcon />,
  AspectRatioIcon: <AspectRatioIcon />,
  CropFreeIcon: <CropFreeIcon />,
  CropIcon: <CropIcon />,
  TransformIcon: <TransformIcon />,
  TuneIcon: <TuneIcon />,
  FilterListIcon: <FilterListIcon />,
  SortIcon: <SortIcon />,
  ImportExportIcon: <ImportExportIcon />,
  SwapVertIcon: <SwapVertIcon />,
  SwapHorizIcon: <SwapHorizIcon />,
  CompareArrowsIcon: <CompareArrowsIcon />,
  CodeIcon: <CodeIcon />,
  TerminalIcon: <TerminalIcon />,
  DeveloperModeIcon: <DeveloperModeIcon />,
  BugReportIcon: <BugReportIcon />,
  BuildIcon: <BuildIcon />,
  ConstructionIcon: <ConstructionIcon />,
  EngineeringIcon: <EngineeringIcon />,
  HandymanIcon: <HandymanIcon />,
  ExtensionIcon: <ExtensionIcon />,
  PluginIcon: <PluginIcon />,
  ApiIcon: <ApiIcon />,
  IntegrationIcon: <IntegrationIcon />,
  HubIcon: <HubIcon />,
  AccountTreeIcon: <AccountTreeIcon />,
  SchemaIcon: <SchemaIcon />,
  DataObjectIcon: <DataObjectIcon />,
  FunctionsIcon: <FunctionsIcon />,
  DatabaseIcon: <DatabaseIcon />,
  TableChartIcon: <TableChartIcon />,
  ViewListIcon: <ViewListIcon />,
  ViewModuleIcon: <ViewModuleIcon />,
  ViewQuiltIcon: <ViewQuiltIcon />,
  ViewStreamIcon: <ViewStreamIcon />,
  ViewArrayIcon: <ViewArrayIcon />,
  ViewColumnIcon: <ViewColumnIcon />,
  ViewCarouselIcon: <ViewCarouselIcon />,
  ViewComfyIcon: <ViewComfyIcon />,
  ViewCompactIcon: <ViewCompactIcon />,
  ViewAgendaIcon: <ViewAgendaIcon />,
  ViewDayIcon: <ViewDayIcon />,
  ViewWeekIcon: <ViewWeekIcon />,
  CalendarViewDayIcon: <CalendarViewDayIcon />,
  CalendarViewWeekIcon: <CalendarViewWeekIcon />,
  CalendarViewMonthIcon: <CalendarViewMonthIcon />,
  EventNoteIcon: <EventNoteIcon />,
  EventAvailableIcon: <EventAvailableIcon />,
  EventBusyIcon: <EventBusyIcon />,
  EventSeatIcon: <EventSeatIcon />,
  MeetingRoomIcon: <MeetingRoomIcon />,
  RoomIcon: <RoomIcon />,
  RoomServiceIcon: <RoomServiceIcon />,
  BedIcon: <BedIcon />,
  BathtubIcon: <BathtubIcon />,
  ShowerIcon: <ShowerIcon />,
  KitchenIcon: <KitchenIcon />,
  DiningIcon: <DiningIcon />,
  WeekendIcon: <WeekendIcon />,
  ChairIcon: <ChairIcon />,
  DeskIcon: <DeskIcon />,
  TableIcon: <TableIcon />,
  CouchIcon: <CouchIcon />,
  SingleBedIcon: <SingleBedIcon />,
  KingBedIcon: <KingBedIcon />,
  CribIcon: <CribIcon />,
  BabyIcon: <BabyIcon />,
  ChildCareIcon: <ChildCareIcon />,
  MenuBookIcon: <MenuBookIcon />,
  BookIcon: <BookIcon />,
  LibraryBooksIcon: <LibraryBooksIcon />,
  AutoStoriesIcon: <AutoStoriesIcon />,
  ImportContactsIcon: <ImportContactsIcon />,
  ChromeReaderModeIcon: <ChromeReaderModeIcon />,
  NoteIcon: <NoteIcon />,
  NoteAddIcon: <NoteAddIcon />,
  EditNoteIcon: <EditNoteIcon />,
  CreateIcon: <CreateIcon />,
  DrawIcon: <DrawIcon />,
  GestureIcon: <GestureIcon />,
  TouchAppIcon: <TouchAppIcon />,
  PanToolIcon: <PanToolIcon />,
  BackIcon: <BackIcon />,
  UndoIcon: <UndoIcon />,
  RedoIcon: <RedoIcon />,
  RefreshIcon: <RefreshIcon />,
  SyncIcon: <SyncIcon />,
  LoopIcon: <LoopIcon />,
  RepeatIcon: <RepeatIcon />,
  RepeatOneIcon: <RepeatOneIcon />,
  ShuffleIcon: <ShuffleIcon />,
  SkipPreviousIcon: <SkipPreviousIcon />,
  SkipNextIcon: <SkipNextIcon />,
  FastRewindIcon: <FastRewindIcon />,
  FastForwardIcon: <FastForwardIcon />,
  PlayArrowIcon: <PlayArrowIcon />,
  PauseIcon: <PauseIcon />,
  StopIcon: <StopIcon />,
  ReplayIcon: <ReplayIcon />,
  Forward10Icon: <Forward10Icon />,
  Replay10Icon: <Replay10Icon />,
  Forward30Icon: <Forward30Icon />,
  Replay30Icon: <Replay30Icon />,
  SlowMotionVideoIcon: <SlowMotionVideoIcon />,
  HighQualityIcon: <HighQualityIcon />,
  HdIcon: <HdIcon />,
  FourKIcon: <FourKIcon />,
  EightKIcon: <EightKIcon />,
  VideoSettingsIcon: <VideoSettingsIcon />,
  SubtitlesIcon: <SubtitlesIcon />,
  ClosedCaptionIcon: <ClosedCaptionIcon />,
  VolumeUpIcon: <VolumeUpIcon />,
  VolumeDownIcon: <VolumeDownIcon />,
  VolumeMuteIcon: <VolumeMuteIcon />,
  VolumeOffIcon: <VolumeOffIcon />,
  MicIcon: <MicIcon />,
  MicOffIcon: <MicOffIcon />,
  MicNoneIcon: <MicNoneIcon />,
  MicExternalOnIcon: <MicExternalOnIcon />,
  MicExternalOffIcon: <MicExternalOffIcon />,
  RecordVoiceOverIcon: <RecordVoiceOverIcon />,
  VoiceChatIcon: <VoiceChatIcon />,
  VoiceOverOffIcon: <VoiceOverOffIcon />,
  HearingIcon: <HearingIcon />,
  HearingDisabledIcon: <HearingDisabledIcon />,
  AssistiveMotionTechnologyIcon: <AssistiveMotionTechnologyIcon />,
  AccessibleIcon: <AccessibleIcon />,
  AccessibleForwardIcon: <AccessibleForwardIcon />,
  WheelchairIcon: <WheelchairIcon />,
  ElderlyCareIcon: <ElderlyCareIcon />,
  HealthAndSafetyIcon: <HealthAndSafetyIcon />,
  MedicalServicesIcon: <MedicalServicesIcon />,
  LocalPharmacyIcon: <LocalPharmacyIcon />,
  VaccinesIcon: <VaccinesIcon />,
  CoronavirusIcon: <CoronavirusIcon />,
  MasksIcon: <MasksIcon />,
  CleanHandsIcon: <CleanHandsIcon />,
  SanitizerIcon: <SanitizerIcon />,
  SoapIcon: <SoapIcon />,
  HotTubIcon: <HotTubIcon />,
  PoolIcon: <PoolIcon />,
  BeachIcon: <BeachIcon />,
  WavesIcon: <WavesIcon />,
  WaterIcon: <WaterIcon />,
  WaterDropIcon: <WaterDropIcon />,
  OpacityIcon: <OpacityIcon />,
  InvertColorsIcon: <InvertColorsIcon />,
  FormatColorFillIcon: <FormatColorFillIcon />,
  FormatColorResetIcon: <FormatColorResetIcon />,
  FormatColorTextIcon: <FormatColorTextIcon />,
  TextFieldsIcon: <TextFieldsIcon />,
  TitleIcon: <TitleIcon />,
  FormatSizeIcon: <FormatSizeIcon />,
  FormatBoldIcon: <FormatBoldIcon />,
  FormatItalicIcon: <FormatItalicIcon />,
  FormatUnderlinedIcon: <FormatUnderlinedIcon />,
  FormatStrikethroughIcon: <FormatStrikethroughIcon />,
  FormatClearIcon: <FormatClearIcon />,
  FormatAlignLeftIcon: <FormatAlignLeftIcon />,
  FormatAlignCenterIcon: <FormatAlignCenterIcon />,
  FormatAlignRightIcon: <FormatAlignRightIcon />,
  FormatAlignJustifyIcon: <FormatAlignJustifyIcon />,
  FormatIndentIncreaseIcon: <FormatIndentIncreaseIcon />,
  FormatIndentDecreaseIcon: <FormatIndentDecreaseIcon />,
  FormatListBulletedIcon: <FormatListBulletedIcon />,
  FormatListNumberedIcon: <FormatListNumberedIcon />,
  FormatQuoteIcon: <FormatQuoteIcon />,
  LinkIcon: <LinkIcon />,
  LinkOffIcon: <LinkOffIcon />,
  InsertLinkIcon: <InsertLinkIcon />,
  AttachFileIcon: <AttachFileIcon />,
  AttachmentIcon: <AttachmentIcon />,
  InsertDriveFileIcon: <InsertDriveFileIcon />,
  FileCopyIcon: <FileCopyIcon />,
  FileDownloadIcon: <FileDownloadIcon />,
  FileUploadIcon: <FileUploadIcon />,
  FolderOpenIcon: <FolderOpenIcon />,
  FolderSharedIcon: <FolderSharedIcon />,
  FolderSpecialIcon: <FolderSpecialIcon />,
  CreateNewFolderIcon: <CreateNewFolderIcon />,
  DriveFileMoveIcon: <DriveFileMoveIcon />,
  DriveFileRenameOutlineIcon: <DriveFileRenameOutlineIcon />,
  DeleteForeverIcon: <DeleteForeverIcon />,
  DeleteIcon: <DeleteIcon />,
  DeleteOutlineIcon: <DeleteOutlineIcon />,
  DeleteSweepIcon: <DeleteSweepIcon />,
  RestoreFromTrashIcon: <RestoreFromTrashIcon />,
  ArchiveIcon: <ArchiveIcon />,
  UnarchiveIcon: <UnarchiveIcon />,
  InboxIcon: <InboxIcon />,
  OutboxIcon: <OutboxIcon />,
  SendIcon: <SendIcon />,
  ReplyIcon: <ReplyIcon />,
  ReplyAllIcon: <ReplyAllIcon />,
  ForwardIcon: <ForwardIcon />,
  MarkEmailReadIcon: <MarkEmailReadIcon />,
  MarkEmailUnreadIcon: <MarkEmailUnreadIcon />,
  DraftsIcon: <DraftsIcon />,
  MoveToInboxIcon: <MoveToInboxIcon />,
  LabelImportantIcon: <LabelImportantIcon />,
  LabelOffIcon: <LabelOffIcon />,
  NewLabelIcon: <NewLabelIcon />,
  SellIcon: <SellIcon />,
  ShoppingBasketIcon: <ShoppingBasketIcon />,
  AddShoppingCartIcon: <AddShoppingCartIcon />,
  RemoveShoppingCartIcon: <RemoveShoppingCartIcon />,
  ProductionQuantityLimitsIcon: <ProductionQuantityLimitsIcon />,
  Inventory2Icon: <Inventory2Icon />,
  GridViewIcon: <GridViewIcon />,
  SpaceDashboardIcon: <SpaceDashboardIcon />,
  DashboardCustomizeIcon: <DashboardCustomizeIcon />,
  AutoGraphIcon: <AutoGraphIcon />,
  InsightsIcon: <InsightsIcon />,
  TrendingFlatIcon: <TrendingFlatIcon />,
  AreaChartIcon: <AreaChartIcon />,
  DonutSmallIcon: <DonutSmallIcon />,
  EqualizerIcon: <EqualizerIcon />,
  GraphicEqIcon: <GraphicEqIcon />,
  PollIcon: <PollIcon />,
  QueryStatsIcon: <QueryStatsIcon />,
  LeaderboardIcon: <LeaderboardIcon />,
  CloudIcon: <CloudIcon />,
  CloudDoneIcon: <CloudDoneIcon />,
  SystemUpdateIcon: <SystemUpdateIcon />,
  SystemUpdateAltIcon: <SystemUpdateAltIcon />,
  GetAppIcon: <GetAppIcon />,
  PublishIcon: <PublishIcon />,
  DownloadIcon: <DownloadIcon />,
  UploadIcon: <UploadIcon />,
  CloudCircleIcon: <CloudCircleIcon />,
  SyncAltIcon: <SyncAltIcon />,
  SyncDisabledIcon: <SyncDisabledIcon />,
  SyncLockIcon: <SyncLockIcon />,
  SyncProblemIcon: <SyncProblemIcon />,
  RepeatOnIcon: <RepeatOnIcon />,
  RepeatOneOnIcon: <RepeatOneOnIcon />,
  ShuffleOnIcon: <ShuffleOnIcon />,
  AutorenewIcon: <AutorenewIcon />,
  CachedIcon: <CachedIcon />,
  RotateLeftIcon: <RotateLeftIcon />,
  RotateRightIcon: <RotateRightIcon />,
  Rotate90DegreesCcwIcon: <Rotate90DegreesCcwIcon />,
  Rotate90DegreesCwIcon: <Rotate90DegreesCwIcon />,
  FlipCameraAndroidIcon: <FlipCameraAndroidIcon />,
  FlipCameraIosIcon: <FlipCameraIosIcon />,
  FlipIcon: <FlipIcon />,
  FlipToBackIcon: <FlipToBackIcon />,
  FlipToFrontIcon: <FlipToFrontIcon />,
  ThreeDRotationIcon: <ThreeDRotationIcon />,
  ThreeSixtyIcon: <ThreeSixtyIcon />,
  ViewIn3dIcon: <ViewIn3dIcon />,
  ThreePIcon: <ThreePIcon />,
  FourMpIcon: <FourMpIcon />,
  FiveMpIcon: <FiveMpIcon />,
  SixMpIcon: <SixMpIcon />,
  SevenMpIcon: <SevenMpIcon />,
  EightMpIcon: <EightMpIcon />,
  NineMpIcon: <NineMpIcon />,
  TenMpIcon: <TenMpIcon />,
  ElevenMpIcon: <ElevenMpIcon />,
  TwelveMpIcon: <TwelveMpIcon />,
  ThirteenMpIcon: <ThirteenMpIcon />,
  FourteenMpIcon: <FourteenMpIcon />,
  FifteenMpIcon: <FifteenMpIcon />,
  SixteenMpIcon: <SixteenMpIcon />,
  SeventeenMpIcon: <SeventeenMpIcon />,
  EighteenMpIcon: <EighteenMpIcon />,
  NineteenMpIcon: <NineteenMpIcon />,
  TwentyMpIcon: <TwentyMpIcon />,
  TwentyOneMpIcon: <TwentyOneMpIcon />,
  TwentyTwoMpIcon: <TwentyTwoMpIcon />,
  TwentyThreeMpIcon: <TwentyThreeMpIcon />,
  TwentyFourMpIcon: <TwentyFourMpIcon />,
};

// Función para obtener icono por nombre
export const getIcon = (iconName) => {
  return iconMap[iconName] || <ArticleIcon />;
};

// Función para obtener componente por nombre
export const getComponent = (componentName) => {
  return componentMap[componentName];
};

// Lista de iconos disponibles para el selector (solo los más comunes)
export const availableIcons = [
  { value: 'DashboardIcon', label: 'Dashboard', icon: <DashboardIcon /> },
  { value: 'BarChartIcon', label: 'Bar Chart', icon: <BarChartIcon /> },
  { value: 'TrendingUpIcon', label: 'Trending Up', icon: <TrendingUpIcon /> },
  { value: 'StorageIcon', label: 'Storage', icon: <StorageIcon /> },
  { value: 'PieChartIcon', label: 'Pie Chart', icon: <PieChartIcon /> },
  { value: 'PeopleIcon', label: 'People', icon: <PeopleIcon /> },
  { value: 'SecurityIcon', label: 'Security', icon: <SecurityIcon /> },
  { value: 'VpnKeyIcon', label: 'Key', icon: <VpnKeyIcon /> },
  { value: 'GroupIcon', label: 'Group', icon: <GroupIcon /> },
  { value: 'PersonIcon', label: 'Person', icon: <PersonIcon /> },
  { value: 'ChatIcon', label: 'Chat', icon: <ChatIcon /> },
  { value: 'ViewKanbanIcon', label: 'Kanban', icon: <ViewKanbanIcon /> },
  { value: 'MailIcon', label: 'Mail', icon: <MailIcon /> },
  { value: 'CalendarTodayIcon', label: 'Calendar', icon: <CalendarTodayIcon /> },
  { value: 'ArticleIcon', label: 'Article', icon: <ArticleIcon /> },
  { value: 'SettingsIcon', label: 'Settings', icon: <SettingsIcon /> },
  { value: 'AppsIcon', label: 'Apps', icon: <AppsIcon /> },
  { value: 'WidgetsIcon', label: 'Widgets', icon: <WidgetsIcon /> },
  { value: 'CategoryIcon', label: 'Category', icon: <CategoryIcon /> },
  { value: 'ListIcon', label: 'List', icon: <ListIcon /> },
  { value: 'AddIcon', label: 'Add', icon: <AddIcon /> },
  { value: 'EditIcon', label: 'Edit', icon: <EditIcon /> },
  { value: 'AssessmentIcon', label: 'Assessment', icon: <AssessmentIcon /> },
  { value: 'BusinessIcon', label: 'Business', icon: <BusinessIcon /> },
  { value: 'ShoppingCartIcon', label: 'Shopping Cart', icon: <ShoppingCartIcon /> },
  { value: 'InventoryIcon', label: 'Inventory', icon: <InventoryIcon /> },
  { value: 'ReceiptIcon', label: 'Receipt', icon: <ReceiptIcon /> },
  { value: 'AccountBoxIcon', label: 'Account Box', icon: <AccountBoxIcon /> },
  { value: 'SupervisorAccountIcon', label: 'Supervisor Account', icon: <SupervisorAccountIcon /> },
  { value: 'AdminPanelSettingsIcon', label: 'Admin Panel', icon: <AdminPanelSettingsIcon /> },
  { value: 'ManageAccountsIcon', label: 'Manage Accounts', icon: <ManageAccountsIcon /> },
  { value: 'FolderIcon', label: 'Folder', icon: <FolderIcon /> },
  { value: 'DescriptionIcon', label: 'Description', icon: <DescriptionIcon /> },
  { value: 'HomeIcon', label: 'Home', icon: <HomeIcon /> },
  { value: 'InfoIcon', label: 'Info', icon: <InfoIcon /> },
  { value: 'HelpIcon', label: 'Help', icon: <HelpIcon /> },
  { value: 'ContactSupportIcon', label: 'Contact Support', icon: <ContactSupportIcon /> },
  { value: 'NotificationsIcon', label: 'Notifications', icon: <NotificationsIcon /> },
  { value: 'LanguageIcon', label: 'Language', icon: <LanguageIcon /> },
  { value: 'PublicIcon', label: 'Public', icon: <PublicIcon /> },
  { value: 'WorkIcon', label: 'Work', icon: <WorkIcon /> },
  { value: 'SchoolIcon', label: 'School', icon: <SchoolIcon /> },
  { value: 'LocalHospitalIcon', label: 'Hospital', icon: <LocalHospitalIcon /> },
  { value: 'RestaurantIcon', label: 'Restaurant', icon: <RestaurantIcon /> },
  { value: 'HotelIcon', label: 'Hotel', icon: <HotelIcon /> },
  { value: 'DirectionsCarIcon', label: 'Car', icon: <DirectionsCarIcon /> },
  { value: 'FlightIcon', label: 'Flight', icon: <FlightIcon /> },
  { value: 'TrainIcon', label: 'Train', icon: <TrainIcon /> },
  { value: 'LocalShippingIcon', label: 'Shipping', icon: <LocalShippingIcon /> },
  { value: 'StoreIcon', label: 'Store', icon: <StoreIcon /> },
  { value: 'StorefrontIcon', label: 'Storefront', icon: <StorefrontIcon /> },
  { value: 'ShoppingBagIcon', label: 'Shopping Bag', icon: <ShoppingBagIcon /> },
  { value: 'PaymentIcon', label: 'Payment', icon: <PaymentIcon /> },
  { value: 'AccountBalanceIcon', label: 'Account Balance', icon: <AccountBalanceIcon /> },
  { value: 'CreditCardIcon', label: 'Credit Card', icon: <CreditCardIcon /> },
  { value: 'MonetizationOnIcon', label: 'Money', icon: <MonetizationOnIcon /> },
];

export default {
  componentMap,
  iconMap,
  getIcon,
  getComponent,
  availableIcons,
};